# Generated by Django 5.2.5 on 2025-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(choices=[('WEAPON_DETECTED', 'Weapon Detected'), ('NO_HELMET', 'No Helmet Detected'), ('NO_VEST', 'No Safety Vest Detected')], max_length=50)),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('clip', models.FileField(blank=True, null=True, upload_to='clips/')),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
