# NVIDIA TensorRT base image (supports GPU + TRT engine)
FROM nvcr.io/nvidia/tensorrt:25.10-py3

WORKDIR /app

#########################################
# Install system dependencies (Ubuntu 24.04 compatible)
#########################################
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

#########################################
# Install Python requirements
#########################################
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

#########################################
# Copy full project
#########################################
COPY . .

#########################################
# Switch to frontend folder
#########################################
WORKDIR /app/Frontend

EXPOSE 5000

#########################################
# Start Flask app
#########################################
CMD ["python", "app.py"]
